/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MatrixMultiplicationJNI */

#ifndef _Included_MatrixMultiplicationJNI
#define _Included_MatrixMultiplicationJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MatrixMultiplicationJNI
 * Method:    computeBenchmark
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MatrixMultiplicationJNI_computeBenchmark
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
