# See supported CPUs here: https://github.com/bazelbuild/platforms/blob/main/cpu/BUILD

config_setting(
    name = "cpu_roborio",
    values = {"cpu": "roborio"},
)

config_setting(
    name = "cpu_pi",
    values = {"cpu": "pi"},
)

#config_setting(
#    name = "k8",
#    values = {"cpu" : "k8},
#)

